/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_Form_GUI;
import java.awt.HeadlessException;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen Moore
 */

public class BankTellerGUI extends javax.swing.JFrame {
    ArrayList<String> Name= new ArrayList<>();
    ArrayList<String> Agebox = new ArrayList<>();
    ArrayList<Integer> Age  = new ArrayList<>();
    ArrayList<String> Gender = new ArrayList<>();
    ArrayList<String> Gendercb = new ArrayList<>();
    ArrayList<String> Address = new ArrayList<>();
    ArrayList<Integer> Balance = new ArrayList<>();
    ArrayList<Boolean> OverDraft = new ArrayList<>();
    ArrayList<Integer> AccountNumber = new ArrayList<>();
    int index;
    /**
     * Creates new form BankTellerGUI
     */
    public BankTellerGUI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UIFullName = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        slideroutput = new javax.swing.JTextArea();
        Ageslider = new javax.swing.JSlider();
        cb1 = new javax.swing.JComboBox<>();
        cboutput = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UIAddress = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        Bal = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        TickBox = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        ACnumber = new javax.swing.JSpinner();
        Usersubmit = new javax.swing.JButton();
        Userdelete = new javax.swing.JButton();
        Userclear = new javax.swing.JButton();
        Userupdate = new javax.swing.JButton();
        Usersearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Useroutput = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Useramount = new javax.swing.JTextArea();
        Permissions = new javax.swing.JTextArea();
        Moneysum = new javax.swing.JTextArea();
        Updatestats = new javax.swing.JButton();
        Male = new javax.swing.JTextArea();
        jlabel22 = new javax.swing.JLabel();
        Female = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        Under = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Over = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        FullName = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        Email = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        Message = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Helpsubmit = new javax.swing.JButton();
        Helpclear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 0, 204));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        //jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bank/cover.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 38)); // NOI18N
        jLabel2.setText(" Welcome to the Bank of Coláiste Dhúlaigh");
        jLabel2.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 10, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel3)
                .addContainerGap(92, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(86, 86, 86)
                .addComponent(jLabel3)
                .addGap(199, 199, 199))
        );

        jTabbedPane1.addTab("Logo", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 0, 204));
        //jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bank/Logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 38)); // NOI18N
        jLabel1.setText("User Information");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 100, 0), 10, true));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setText("Full Name:");

        UIFullName.setColumns(20);
        UIFullName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UIFullName.setRows(5);
        UIFullName.setToolTipText("This is where you enter the clients full name.");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setText("Age:");

        slideroutput.setEditable(false);
        slideroutput.setColumns(20);
        slideroutput.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        slideroutput.setRows(5);
        slideroutput.setToolTipText("This is where the clients age will be");

        Ageslider.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Ageslider.setMajorTickSpacing(10);
        Ageslider.setPaintLabels(true);
        Ageslider.setPaintTicks(true);
        Ageslider.setToolTipText("Please drag the slider to the clients current age");
        Ageslider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                AgesliderMouseDragged(evt);
            }
        });
        Ageslider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgesliderMouseClicked(evt);
            }
        });

        cb1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", "Would Rather Not Say" }));
        cb1.setToolTipText("Please click on the box to choose the clients gender");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cboutput.setEditable(false);
        cboutput.setColumns(20);
        cboutput.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cboutput.setRows(5);
        cboutput.setToolTipText("This is the option for gender you have choosen");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setText("Gender:");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setText("Address:");

        UIAddress.setColumns(20);
        UIAddress.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UIAddress.setRows(5);
        UIAddress.setToolTipText("This is where you enter the clients address");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setText("Balance:");

        Bal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Bal.setToolTipText("This is where you enter the clients current balance");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setText("Overdraft:");

        TickBox.setBackground(java.awt.Color.white);
        TickBox.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        TickBox.setForeground(java.awt.Color.black);
        TickBox.setText("Click if the client has permission for an overdraft ");
        TickBox.setToolTipText("This check box is to show whether the client has permission for an overdraft or not");

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setText("Account Number:");

        ACnumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ACnumber.setModel(new javax.swing.SpinnerNumberModel());
        ACnumber.setToolTipText("Enter the clients account number here");

        Usersubmit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Usersubmit.setText("Submit");
        Usersubmit.setToolTipText("This will submit the clients details");
        Usersubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersubmitMouseClicked(evt);
            }
        });
        Usersubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersubmitActionPerformed(evt);
            }
        });

        Userdelete.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Userdelete.setText("Delete");
        Userdelete.setToolTipText("This will delete the clients details");
        Userdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserdeleteMouseClicked(evt);
            }
        });

        Userclear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Userclear.setText("Clear");
        Userclear.setToolTipText("This button will clear all details in the boxes");
        Userclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserclearMouseClicked(evt);
            }
        });

        Userupdate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Userupdate.setText("Update");
        Userupdate.setToolTipText("This will update the clients details");
        Userupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserupdateActionPerformed(evt);
            }
        });

        Usersearch.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Usersearch.setText("Search ");
        Usersearch.setToolTipText("This will search for the user's details using the clients account number");
        Usersearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsersearchMouseClicked(evt);
            }
        });

        Useroutput.setEditable(false);
        Useroutput.setColumns(20);
        Useroutput.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        Useroutput.setRows(5);
        Useroutput.setToolTipText("This is where the submitted, deleted and updated accounts will be shown ");
        Useroutput.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Useroutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slideroutput, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboutput, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ageslider, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UIAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bal, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TickBox)
                    .addComponent(ACnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UIFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(Usersubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Userdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Userclear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Userupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Usersearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(209, 209, 209))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UIFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slideroutput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(Ageslider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboutput, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UIAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(Bal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(TickBox)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ACnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Usersubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Userclear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Userupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Usersearch, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Userdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("User Information ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 0, 204));

        jLabel4.setBackground(new java.awt.Color(204, 0, 204));
        //jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bank/Logo.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Calibri Light", 1, 38)); // NOI18N
        jLabel18.setText("Bank Statistics");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 105, 30), 10, true));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 33)); // NOI18N
        jLabel19.setText("Number of Clients:");

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 33)); // NOI18N
        jLabel20.setText("Sum of all Money:");

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 33)); // NOI18N
        jLabel21.setText("Overdraft Permissions:");

        Useramount.setEditable(false);
        Useramount.setColumns(20);
        Useramount.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        Useramount.setRows(5);
        Useramount.setText("0");
        Useramount.setToolTipText("This is where you can see the number of users in the bank");

        Permissions.setEditable(false);
        Permissions.setColumns(20);
        Permissions.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        Permissions.setRows(5);
        Permissions.setText("0");
        Permissions.setToolTipText("This shows the amount of people who have overdraft permission");

        Moneysum.setEditable(false);
        Moneysum.setColumns(20);
        Moneysum.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        Moneysum.setRows(5);
        Moneysum.setText("0");
        Moneysum.setToolTipText("This shows the sum of all money in the bank");

        Updatestats.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        Updatestats.setText("Update Statistics");
        Updatestats.setToolTipText("This updates the boxes with the correct information");
        Updatestats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatestatsMouseClicked(evt);
            }
        });

        Male.setEditable(false);
        Male.setColumns(20);
        Male.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        Male.setRows(5);
        Male.setText("0");
        Male.setToolTipText("This shows the number of male clients");

        jlabel22.setFont(new java.awt.Font("Calibri", 1, 33)); // NOI18N
        jlabel22.setText("Number of Male Clients:");

        Female.setEditable(false);
        Female.setColumns(20);
        Female.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        Female.setRows(5);
        Female.setText("0");
        Female.setToolTipText("this shows the number of female clients");

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 33)); // NOI18N
        jLabel22.setText("Number of Female Clients: ");

        Under.setEditable(false);
        Under.setColumns(20);
        Under.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        Under.setRows(5);
        Under.setText("0");
        Under.setToolTipText("this shows the number of clients under 30");

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 33)); // NOI18N
        jLabel23.setText("Number of Clients Under 30:");

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 33)); // NOI18N
        jLabel24.setText("Number of Clients Over 30:");

        Over.setEditable(false);
        Over.setColumns(20);
        Over.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        Over.setRows(5);
        Over.setText("0");
        Over.setToolTipText("this shows the number of clients over 30");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(239, 239, 239))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Under, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Moneysum, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Useramount, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Male, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Female, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Permissions, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Over, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(Updatestats, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Useramount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(Moneysum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(Permissions, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel22)
                    .addComponent(Male, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Female, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(Under, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Over, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(Updatestats, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("Bank Statistics ", jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 0, 204));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 33)); // NOI18N
        jLabel11.setText("Full Name:");
        jLabel11.setToolTipText("Please enter your full name in the box to the right :) ");

        FullName.setColumns(20);
        FullName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FullName.setLineWrap(true);
        FullName.setRows(5);
        FullName.setToolTipText("Please Enter Full Name Here");
        FullName.setWrapStyleWord(true);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 33)); // NOI18N
        jLabel12.setText("Email Address:");
        jLabel12.setToolTipText("Please enter your email address in the box to the right :) ");

        Email.setColumns(20);
        Email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Email.setLineWrap(true);
        Email.setRows(5);
        Email.setToolTipText("Please Enter Your Email Here");
        Email.setWrapStyleWord(true);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 33)); // NOI18N
        jLabel13.setText("Message:");
        jLabel13.setToolTipText("Please enter the message in the box to the right :) ");

        Message.setColumns(20);
        Message.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Message.setLineWrap(true);
        Message.setRows(5);
        Message.setToolTipText("Please Enter Your Message or Problem Here");
        Message.setWrapStyleWord(true);

        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 38)); // NOI18N
        jLabel14.setText("Help Desk");
        jLabel14.setBorder(new javax.swing.border.LineBorder(java.awt.Color.blue, 10, true));

        //jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bank/Logo.png"))); // NOI18N

        Helpsubmit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Helpsubmit.setText("Submit");
        Helpsubmit.setToolTipText("This will submit your message");
        Helpsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpsubmitMouseClicked(evt);
            }
        });

        Helpclear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Helpclear.setText("Clear");
        Helpclear.setToolTipText("this will clear the boxes");
        Helpclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpclearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Email)
                            .addComponent(FullName)
                            .addComponent(Message)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Helpsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Helpclear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(213, 213, 213))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Helpclear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Helpsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        Message.getAccessibleContext().setAccessibleName("Message");

        jTabbedPane1.addTab("Help Desk", jPanel5);

        jPanel4.setBackground(new java.awt.Color(204, 0, 204));

        jLabel26.setFont(new java.awt.Font("Calibri Light", 1, 38)); // NOI18N
        jLabel26.setText("Logout");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red, 10));

        Exit.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Exit.setText("Logout");
        Exit.setToolTipText("Press this to logout");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        //jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bank/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(jLabel26))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26))
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        jTabbedPane1.addTab("Logout", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tab1");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");
        jTabbedPane1.getAccessibleContext().setAccessibleParent(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HelpsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpsubmitMouseClicked
        // TODO add your handling code here:if (Email=="@") 
        try{//strat try
            String emai1 = Email.getText();
            String Emailcheck = "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}\\b";
            Pattern p = Pattern.compile(Emailcheck);
            Matcher m = p.matcher(emai1);
            String name = FullName.getText();
            String Namecheck;
            Namecheck = "\\b[0-9._%+-;@#~!£$%^&*=,.<>/?`¬]{1,100}\\b";
            Pattern d = Pattern.compile(Namecheck);
            Matcher f = d.matcher(name);
           
            if(f.find()|FullName.getText().isEmpty() | Email.getText().isEmpty()|Message.getText().isEmpty() ){//start if    
                JOptionPane.showMessageDialog(null, "Please Enter What is Required in Each Box."); 
            } //end if
            else  {//start else
                 if(m.find()){//start if
            JOptionPane.showMessageDialog(null,"Thank you for the message we will reply as soon as possible.");  
            }//end if
            }//end else
        }//end try
        catch(HeadlessException e){//start catch
            JOptionPane.showMessageDialog(null, "Please Only Use Letter and Numbers Where Asked");  
        }//end catch
    }//GEN-LAST:event_HelpsubmitMouseClicked

    private void HelpclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpclearMouseClicked
        FullName.setText("");
        Email.setText("");
        Message.setText("");
    }//GEN-LAST:event_HelpclearMouseClicked

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        cboutput.setText(cb1.getSelectedItem().toString());
    }//GEN-LAST:event_cb1ActionPerformed

    private void AgesliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgesliderMouseDragged
      int num1 = Ageslider.getValue();
      String str1 = Integer.toString(num1);
      slideroutput.setText(str1);  
    }//GEN-LAST:event_AgesliderMouseDragged

    private void UsersubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersubmitMouseClicked
        // TODO add your handling code here:         
    }//GEN-LAST:event_UsersubmitMouseClicked

    private void UserclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserclearMouseClicked
        // TODO add your handling code here:
        UIFullName.setText("");
        slideroutput.setText("");
        Ageslider.setValue(50);
        cboutput.setText("");
        UIAddress.setText("");
        Bal.setValue(0);
        ACnumber.setValue(0);
        TickBox.setSelected(false);
    }//GEN-LAST:event_UserclearMouseClicked

    private void UsersubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersubmitActionPerformed
        // TODO add your handling code here:
        try{//start try
            String name = UIFullName.getText();
            String Namecheck;
            Namecheck = "\\b[0-9._%+-;@#~!£$%^&*=,.<>/?`¬]{1,100}\\b";
            Pattern p = Pattern.compile(Namecheck);
            Matcher m = p.matcher(name);
            int acnumber1 = (int) ACnumber.getValue();
            int id1 = acnumber1;
            boolean found1 = AccountNumber.contains(id1);
            if(m.find()|found1==true|Bal.getValue().equals(0)|ACnumber.getValue().equals(0)|UIFullName.getText().isEmpty() | slideroutput.getText().isEmpty()|cboutput.getText().isEmpty()|UIAddress.getText().isEmpty()){//start if
                JOptionPane.showMessageDialog(null,"User could not be created");
                JOptionPane.showMessageDialog(null,"Please make sure account number or balance is not 0, no numbers in Full Name box, the account number isn't in use and that no box is empty unless it's the check box.");
            }//end if 
            else {//start else
                Name.add(UIFullName.getText());
                Age.add((Integer)Ageslider.getValue());
                Agebox.add(slideroutput.getText());
                Gender.add(cboutput.getText());
                Gendercb.add(cb1.getActionCommand());
                Address.add(UIAddress.getText());
                Balance.add((Integer) Bal.getValue());
                OverDraft.add(TickBox.isSelected());
                AccountNumber.add((Integer) ACnumber.getValue());
                JOptionPane.showMessageDialog(null, "Account Created");
                Useroutput.append("************************\n");
                Useroutput.append("Full Name: "+UIFullName.getText()+"\n");
                Useroutput.append("Age: "+Ageslider.getValue()+"\n");
                Useroutput.append("Gender: "+cboutput.getText()+"\n");
                Useroutput.append("Address: "+UIAddress.getText()+"\n");
                Useroutput.append("Balance: "+Bal.getValue()+"\n");
                Useroutput.append("Overdraft: "+TickBox.isSelected()+"\n");
                Useroutput.append("Account Number: "+ACnumber.getValue()+"\n");
                Useroutput.append("************************\n");
            }//end else 
        } //end try
        catch(HeadlessException e) {//start catch
            JOptionPane.showMessageDialog(null, "Please Only Enter Numbers and Letters Where They are Needed");   
        }//end catch
    }//GEN-LAST:event_UsersubmitActionPerformed

    private void UserdeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserdeleteMouseClicked
      // TODO add your handling code here:
       try{//start try
            int number = (int) ACnumber.getValue();
            int id = number;
            boolean found = AccountNumber.contains(id); 
            index=AccountNumber.indexOf(id);
            if(found==false){//start if
             JOptionPane.showMessageDialog(null, "Account Could Not Be Deleted Please Make Sure That You Have The Correct Account Number");
            }//end if 
            else if (found==true){
            UIFullName.setText(Name.get(index));
            Ageslider.setValue(Age.get(index));
            slideroutput.setText(Agebox.get(index));
            cboutput.setText(Gender.get(index));
            UIAddress.setText(Address.get(index));
            Bal.setValue(Balance.get(index));
            TickBox.setSelected(OverDraft.get(index));
            ACnumber.setValue(number);   
            Useroutput.append("************************\n");
            Useroutput.append("Name: "+UIFullName.getText()+" ----Deleted\n");
            Useroutput.append("Account Number: "+ACnumber.getValue()+" ----Deleted\n");
            Useroutput.append("************************\n");
            Name.remove(index);
            Age.remove(index);
            Agebox.remove(index);
            Gender.remove(index);
            Gendercb.remove(index);
            Address.remove(index);
            Balance.remove(index);
            OverDraft.remove(index);
            AccountNumber.remove(index);
            UIFullName.setText("");
            slideroutput.setText("");
            Ageslider.setValue(50);
            cboutput.setText("");
            UIAddress.setText("");
            Bal.setValue(0);
            ACnumber.setValue(0);
            TickBox.setSelected(false);
            JOptionPane.showMessageDialog(null, "Account Deleted");
            }//end else
        }//end try
        catch (HeadlessException e){//start catch
            JOptionPane.showMessageDialog(null, "Account Could Not Be Deleted");
        }//end catch
    }//GEN-LAST:event_UserdeleteMouseClicked

    private void UsersearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsersearchMouseClicked
        // TODO add your handling code here:
        try{//start try
            int number = (int) ACnumber.getValue();
            int id = number;
            boolean found = AccountNumber.contains(id);
            index=AccountNumber.indexOf(id);
            if (found == false ){//start if
                JOptionPane.showMessageDialog(null, "Account Not Found, Please Try Again");
                UIFullName.setText("");
                Ageslider.setValue(50);
                slideroutput.setText("");
                cboutput.setText("");
                UIAddress.setText("");
                Bal.setValue(0);
                TickBox.setSelected(false);
                ACnumber.setValue(0);
            }//end if
            else if(found == true){//start else
                UIFullName.setText(Name.get(index));
                Ageslider.setValue(Age.get(index));
                slideroutput.setText(Agebox.get(index));
                cboutput.setText(Gender.get(index));
                UIAddress.setText(Address.get(index));
                Bal.setValue(Balance.get(index));
                TickBox.setSelected(OverDraft.get(index));
                ACnumber.setValue(number);
                JOptionPane.showMessageDialog(null, "Account Found");
            }//end else
        }//end try
        catch(HeadlessException e){//start catch
            JOptionPane.showMessageDialog(null, "Could not search "+e);
        }//end catch
    }//GEN-LAST:event_UsersearchMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_jPanel2MouseClicked

    private void UserupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserupdateActionPerformed
        // TODO add your handling code here:
        try{//start try
            String name = UIFullName.getText();
            String Namecheck;
            Namecheck = "\\b[0-9._%+-;@#~!£$%^&*=,.<>/?`¬]{1,100}\\b";
            Pattern p = Pattern.compile(Namecheck);
            Matcher m = p.matcher(name);
            if(m.find()|ACnumber.getValue().equals(0)|UIFullName.getText().isEmpty() | slideroutput.getText().isEmpty()|cboutput.getText().isEmpty()|UIAddress.getText().isEmpty()){//start if
                JOptionPane.showMessageDialog(null, "Account Couldn't be updated");
                JOptionPane.showMessageDialog(null, "Please make sure account number is not 0, no numbers in Full box, the account number isn't in use and that no box is empty unless it's the check box.");
            }///end if
                else{//start else            
                Name.set(index,UIFullName.getText());
                Agebox.set(index,slideroutput.getText());
                Age.set(index,Ageslider.getValue());
                Gender.set(index,cboutput.getText());
                Gendercb.set(index,cb1.getActionCommand());
                Address.set(index,UIAddress.getText());
                Balance.set(index,(Integer) Bal.getValue());
                OverDraft.set(index,(Boolean)TickBox.isSelected());
                AccountNumber.set(index,(Integer)ACnumber.getValue());
                JOptionPane.showMessageDialog(null, "Account Updated");
                Useroutput.append("************************\n");
                Useroutput.append("Full Name: "+UIFullName.getText()+"\n");
                Useroutput.append("Age: "+Ageslider.getValue()+"\n");
                Useroutput.append("Gender: "+cboutput.getText()+"\n");
                Useroutput.append("Address: "+UIAddress.getText()+"\n");
                Useroutput.append("Balance: "+Bal.getValue()+"\n");
                Useroutput.append("Overdraft: "+TickBox.isSelected()+"\n");
                Useroutput.append("Account Number: "+ACnumber.getValue()+"\n");
                Useroutput.append("************************\n");
            }//end else 
        }//end try
        catch(HeadlessException | NumberFormatException e) {//start try
            JOptionPane.showMessageDialog(null, "Please Only Enter Numbers and Letters Where They are Needed");   
        }//end try
    }//GEN-LAST:event_UserupdateActionPerformed

    private void UpdatestatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatestatsMouseClicked
        // TODO add your handling code here:        
        
        try{
            int ACnum1 = AccountNumber.size();
            String ACnum2 = String.valueOf(ACnum1);
            Useramount.setText(ACnum2);
            
            int count = 0;
            for(Boolean value : OverDraft){//start for
                if(value==true){//start if
                    count++;
                }//end if
            }//end for
            String over = Integer.toString(count);
            Permissions.setText(over);
        
            int sum = 0;
            for(int Money : Balance){//start for
                sum += Money;
                String Sumof = String.valueOf(sum);
                Moneysum.setText(Sumof);
                  if(Balance.isEmpty()){
                  Moneysum.setText("0");
                    }//end if
            }//end for
            for(String Malenum2:Gender){//start for
                if(Gender.contains("Male")){//start if
                    String Malenum3 = String.valueOf(count);
                    Male.setText(Malenum3);
                }//end if
                else{
               if (Gender.isEmpty()){
                   Male.setText("0");  
               }//end if
                }//end else
            }//end for
            for(String Femalenum2:Gender){//start for
                if(Gender.contains("Female")){//start if
                    String Femalenum3 = String.valueOf(count);
                    Female.setText(Femalenum3);  
                }//end if
                else{
                    if (Gender.isEmpty()){
                        Female.setText("0");  
                    }//end if
                }//end else
                    
            }//end for
        
            for(int under1:Age){//start for
                if(Age.get(index)<=30){//start if
                    String under2 = String.valueOf(count);
                    Under.setText(under2);
            }//end if
                }//start for
            
            for(int Over1:Age){//startt for
                if(Age.get(index)>30){//start if
                    String Over2 = String.valueOf(count);
                    Over.setText(Over2);
                }//end if
            }//end for
        }//end try
        catch(Exception e){//start catch
            JOptionPane.showMessageDialog(null, "There is a Problem Please Try Again.");
        }//end catch
         
    }//GEN-LAST:event_UpdatestatsMouseClicked

    private void AgesliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgesliderMouseClicked
        // TODO add your handling code here:
      int num1 = Ageslider.getValue();
      String str1 = Integer.toString(num1);
      slideroutput.setText(str1);  
    }//GEN-LAST:event_AgesliderMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog( Exit,"confirm if you Want to Exit","BankTellerGUI",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankTellerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankTellerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankTellerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankTellerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BankTellerGUI().setVisible(true);
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ACnumber;
    private javax.swing.JSlider Ageslider;
    private javax.swing.JSpinner Bal;
    private javax.swing.JTextArea Email;
    private javax.swing.JButton Exit;
    private javax.swing.JTextArea Female;
    private javax.swing.JTextArea FullName;
    private javax.swing.JButton Helpclear;
    private javax.swing.JButton Helpsubmit;
    private javax.swing.JTextArea Male;
    private javax.swing.JTextArea Message;
    private javax.swing.JTextArea Moneysum;
    private javax.swing.JTextArea Over;
    private javax.swing.JTextArea Permissions;
    private javax.swing.JCheckBox TickBox;
    private javax.swing.JTextArea UIAddress;
    private javax.swing.JTextArea UIFullName;
    private javax.swing.JTextArea Under;
    private javax.swing.JButton Updatestats;
    private javax.swing.JTextArea Useramount;
    private javax.swing.JButton Userclear;
    private javax.swing.JButton Userdelete;
    private javax.swing.JTextArea Useroutput;
    private javax.swing.JButton Usersearch;
    private javax.swing.JButton Usersubmit;
    private javax.swing.JButton Userupdate;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JTextArea cboutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlabel22;
    private javax.swing.JTextArea slideroutput;
    // End of variables declaration//GEN-END:variables
}
